### ISSUE TITLE
Slugrunner unable to start due to shelf error

### ISSUE THREAD

**Issue by jayd3e** [flynn-archive/shelf#8]
Slugrunner is attempting to start the app, but isn't able to pull down the slug due to an error in shelf.  Attempting to wget the slug fails as well:

```
vagrant /opt/webapp/clusterflunk/src $ wget http://<ip>:55004/<release id>.tgz
--2014-04-27 19:54:37--  http://<ip>:55004/<release_id>.tgz
Connecting to <ip>:55004... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2014-04-27 19:54:38 ERROR 500: Internal Server Error.
```

Here is the logs from `kill -QUIT $pid`:

```
root@clusterflunk-flynn:~/src/gopkgs/src/github.com/flynn/flynn-bootstrap/bootstrapper# docker logs 7d5030e1b4f7
2014/04/27 19:41:45 PUT /7ab150e5d23020a18635e934697d18771cd4749f.tgz
2014/04/27 19:45:16 GET /7ab150e5d23020a18635e934697d18771cd4749f.tgz
2014/04/27 19:45:22 GET /7ab150e5d23020a18635e934697d18771cd4749f.tgz
2014/04/27 19:45:29 GET /7ab150e5d23020a18635e934697d18771cd4749f.tgz
2014/04/27 19:45:35 GET /7ab150e5d23020a18635e934697d18771cd4749f.tgz
2014/04/27 19:45:41 GET /7ab150e5d23020a18635e934697d18771cd4749f.tgz
2014/04/27 19:45:47 GET /7ab150e5d23020a18635e934697d18771cd4749f.tgz
2014/04/27 19:45:54 GET /7ab150e5d23020a18635e934697d18771cd4749f.tgz
2014/04/27 19:47:04 GET /7ab150e5d23020a18635e934697d18771cd4749f.tgz
2014/04/27 19:47:11 GET /7ab150e5d23020a18635e934697d18771cd4749f.tgz
2014/04/27 19:48:20 error: pq: unexpected transaction status idle in transaction
2014/04/27 19:49:23 error: pq: unexpected transaction status idle in transaction
2014/04/27 19:50:27 error: pq: unexpected transaction status idle in transaction
2014/04/27 19:51:15 error: pq: unexpected transaction status idle in transaction
2014/04/27 19:51:16 error: pq: unexpected transaction status idle in transaction
2014/04/27 19:51:21 error: pq: unexpected transaction status idle in transaction
2014/04/27 19:51:22 error: pq: unexpected transaction status idle in transaction
2014/04/27 19:51:23 error: pq: unexpected transaction status idle in transaction
2014/04/27 19:52:11 error: pq: unexpected transaction status idle in transaction
2014/04/27 19:52:43 error: pq: unexpected transaction status idle in transaction
2014/04/27 19:53:30 error: pq: unexpected transaction status idle in transaction
2014/04/27 19:54:18 error: pq: unexpected transaction status idle in transaction
2014/04/27 19:54:38 error: pq: unexpected transaction status idle in transaction
2014/04/27 19:55:06 error: pq: unexpected transaction status idle in transaction
2014/04/27 19:55:53 error: pq: unexpected transaction status idle in transaction
2014/04/27 19:56:41 error: pq: unexpected transaction status idle in transaction
2014/04/27 19:57:29 error: pq: unexpected transaction status idle in transaction
2014/04/27 19:58:16 error: pq: unexpected transaction status idle in transaction
2014/04/27 19:59:04 error: pq: unexpected transaction status idle in transaction
SIGQUIT: quit
PC=0x428fb3

runtime.notetsleepg(0x7fb24fcadf60, 0xdf8475800)
    /usr/local/go/src/pkg/runtime/lock_futex.c:190 +0x46 fp=0x7fb24fcadf38
runtime.MHeap_Scavenger()
    /usr/local/go/src/pkg/runtime/mheap.c:463 +0xa3 fp=0x7fb24fcadfa0
runtime.goexit()
    /usr/local/go/src/pkg/runtime/proc.c:1394 fp=0x7fb24fcadfa8
created by runtime.main
    /usr/local/go/src/pkg/runtime/proc.c:179

goroutine 1 [IO wait]:
net.runtime_pollWait(0x7fb24fe30460, 0x72, 0x0)
    /usr/local/go/src/pkg/runtime/netpoll.goc:116 +0x6a
net.(*pollDesc).Wait(0xc210096ed0, 0x72, 0x7fb24fe2f098, 0xb)
    /usr/local/go/src/pkg/net/fd_poll_runtime.go:81 +0x34
net.(*pollDesc).WaitRead(0xc210096ed0, 0xb, 0x7fb24fe2f098)
    /usr/local/go/src/pkg/net/fd_poll_runtime.go:86 +0x30
net.(*netFD).accept(0xc210096e70, 0x7cea38, 0x0, 0x7fb24fe2f098, 0xb)
    /usr/local/go/src/pkg/net/fd_unix.go:382 +0x2c2
net.(*TCPListener).AcceptTCP(0xc210000f48, 0x48184b, 0x7fb24fc8fd88, 0x48184b)
    /usr/local/go/src/pkg/net/tcpsock_posix.go:233 +0x47
net.(*TCPListener).Accept(0xc210000f48, 0x7fb24fe2f5e8, 0xc2100af140, 0xc2100ace00, 0x0)
    /usr/local/go/src/pkg/net/tcpsock_posix.go:243 +0x27
net/http.(*Server).Serve(0xc2100a65a0, 0x7fb24fe30fe0, 0xc210000f48, 0x0, 0x0)
    /usr/local/go/src/pkg/net/http/server.go:1622 +0x91
net/http.(*Server).ListenAndServe(0xc2100a65a0, 0xc2100a65a0, 0xc2100989f0)
    /usr/local/go/src/pkg/net/http/server.go:1612 +0xa0
net/http.ListenAndServe(0xc210000340, 0x6, 0x7fb24fe30fb8, 0xc2100989f0, 0x0, ...)
    /usr/local/go/src/pkg/net/http/server.go:1677 +0x6d
main.main()
    /home/vagrant/shelf/shelf.go:95 +0x37f

goroutine 4 [IO wait]:
net.runtime_pollWait(0x7fb24fe305b0, 0x72, 0x0)
    /usr/local/go/src/pkg/runtime/netpoll.goc:116 +0x6a
net.(*pollDesc).Wait(0xc210057bc0, 0x72, 0x7fb24fe2f098, 0xb)
    /usr/local/go/src/pkg/net/fd_poll_runtime.go:81 +0x34
net.(*pollDesc).WaitRead(0xc210057bc0, 0xb, 0x7fb24fe2f098)
    /usr/local/go/src/pkg/net/fd_poll_runtime.go:86 +0x30
net.(*netFD).Read(0xc210057b60, 0xc210094000, 0x1000, 0x1000, 0x0, ...)
    /usr/local/go/src/pkg/net/fd_unix.go:204 +0x2a0
net.(*conn).Read(0xc210000360, 0xc210094000, 0x1000, 0x1000, 0x7fb24fe26000, ...)
    /usr/local/go/src/pkg/net/net.go:122 +0xc5
bufio.(*Reader).fill(0xc2100383c0)
    /usr/local/go/src/pkg/bufio/bufio.go:91 +0x110
bufio.(*Reader).Read(0xc2100383c0, 0xc21004cc70, 0x1, 0x9, 0x1, ...)
    /usr/local/go/src/pkg/bufio/bufio.go:159 +0x1a4
io.ReadAtLeast(0x7fb24fe306f8, 0xc2100383c0, 0xc21004cc70, 0x1, 0x9, ...)
    /usr/local/go/src/pkg/io/io.go:288 +0xf6
io.ReadFull(0x7fb24fe306f8, 0xc2100383c0, 0xc21004cc70, 0x1, 0x9, ...)
    /usr/local/go/src/pkg/io/io.go:306 +0x71
encoding/gob.decodeUintReader(0x7fb24fe306f8, 0xc2100383c0, 0xc21004cc70, 0x9, 0x9, ...)
    /usr/local/go/src/pkg/encoding/gob/decode.go:66 +0x98
encoding/gob.(*Decoder).recvMessage(0xc210093000, 0xc210037d00)
    /usr/local/go/src/pkg/encoding/gob/decoder.go:73 +0x57
encoding/gob.(*Decoder).decodeTypeSequence(0xc210093000, 0xc210082f00, 0x160)
    /usr/local/go/src/pkg/encoding/gob/decoder.go:159 +0x49
encoding/gob.(*Decoder).DecodeValue(0xc210093000, 0x631460, 0xc210082fc0, 0x160, 0x0, ...)
    /usr/local/go/src/pkg/encoding/gob/decoder.go:223 +0x12e
encoding/gob.(*Decoder).Decode(0xc210093000, 0x631460, 0xc210082fc0, 0xc210053298, 0xc2100aee70)
    /usr/local/go/src/pkg/encoding/gob/decoder.go:202 +0x1c5
github.com/flynn/rpcplus.(*gobClientCodec).ReadResponseHeader(0xc210082b70, 0xc210082fc0, 0xc2100983d0, 0x0)
    /tmp/godep/rev/0f/5f55ccd60369cfc32008d9c955e6b19cdb15e6/src/github.com/flynn/rpcplus/client.go:277 +0x3f
github.com/flynn/rpcplus.(*Client).input(0xc210038420)
    /tmp/godep/rev/0f/5f55ccd60369cfc32008d9c955e6b19cdb15e6/src/github.com/flynn/rpcplus/client.go:137 +0xb8
created by github.com/flynn/rpcplus.NewClientWithCodec
    /tmp/godep/rev/0f/5f55ccd60369cfc32008d9c955e6b19cdb15e6/src/github.com/flynn/rpcplus/client.go:255 +0x91

goroutine 5 [chan receive]:
github.com/flynn/go-discoverd.func·001()
    /tmp/godep/rev/c2/36937e9dd13e2e85314a9ab8cdadff52452601/src/github.com/flynn/go-discoverd/client.go:123 +0x5b
created by github.com/flynn/go-discoverd.(*serviceSet).bind
    /tmp/godep/rev/c2/36937e9dd13e2e85314a9ab8cdadff52452601/src/github.com/flynn/go-discoverd/client.go:165 +0xcf

goroutine 6 [chan send]:
github.com/flynn/go-flynn/postgres.(*DB).followLeader(0xc21001fe60, 0xc210038a20)
    /tmp/godep/rev/c9/5262db7474ac09ce1ccbc7a6c81d9a3aef670b/src/github.com/flynn/go-flynn/postgres/postgres.go:46 +0x467
created by github.com/flynn/go-flynn/postgres.Open
    /tmp/godep/rev/c9/5262db7474ac09ce1ccbc7a6c81d9a3aef670b/src/github.com/flynn/go-flynn/postgres/postgres.go:24 +0x132

goroutine 7 [chan receive]:
github.com/flynn/go-sql.(*DB).connectionOpener(0xc21007da00)
    /tmp/godep/rev/f2/272fcc41821d3313c69dc032a9c5dd004005c6/src/github.com/flynn/go-sql/sql.go:596 +0x3e
created by github.com/flynn/go-sql.Open
    /tmp/godep/rev/f2/272fcc41821d3313c69dc032a9c5dd004005c6/src/github.com/flynn/go-sql/sql.go:438 +0x24d

goroutine 8 [select]:
github.com/flynn/go-discoverd.func·005()
    /tmp/godep/rev/c2/36937e9dd13e2e85314a9ab8cdadff52452601/src/github.com/flynn/go-discoverd/client.go:483 +0x2e8
created by github.com/flynn/go-discoverd.(*Client).RegisterWithAttributes
    /tmp/godep/rev/c2/36937e9dd13e2e85314a9ab8cdadff52452601/src/github.com/flynn/go-discoverd/client.go:494 +0x454

rax     0xfffffffffffffffc
rbx     0x0
rcx     0xffffffffffffffff
rdx     0x0
rdi     0x7fb24fcadf60
rsi     0x0
rbp     0x3c
rsp     0x7fb24fcadea0
r8      0x0
r9      0x0
r10     0x7fb24fcaded0
r11     0x216
r12     0x0
r13     0x6
r14     0xc210098720
r15     0x7fb24fe2ee80
rip     0x428fb3
rflags  0x216
cs      0x33
fs      0x0
gs      0x0
```

**Comment by titanous** [comment]
I haven't been able to reproduce locally, do you have a consistent repro case? (preferably starting from bootstrapping the flynn-demo vm)

**Comment by jayd3e** [comment]
Can confirm that this bug does not exist in the current code, it's just in the image that's hosted on flynn/shelf.

**Comment by titanous** [comment]
I've pushed the latest version.

**Comment by jayd3e** [comment]
So this needs to be reopened.  I'm running into this error again, on master.  It only happens after shelf has handled a certain number of requests.

**Comment by titanous** [comment]
Interesting. We really need to come up with a way to reproduce it consistently.

**Comment by jayd3e** [comment]
Yeah I'll look for that consistent way.  I'm pretty sure it has something to do with a certain number of postgres requests hanging or something and taking up the entire connection pool, b/c it feels like it's a very predictable number of requests that happen before this error starts to occur.  Completely a shot in the dark.

**Comment by jayd3e** [comment]
This can be reproduced by just deploying the system, and then scale a web process up to ~10.  This will cause shelf to be used more than it is capable of handling, and it will start to error.  Looking at it now.
